# Generated by Django 3.2.11 on 2022-02-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteCulture',
            fields=[
                ('IdCCulture', models.IntegerField(primary_key=True, serialize=False)),
                ('DescriptionCCulture', models.CharField(max_length=500)),
                ('StartDateCCulture', models.DateField()),
                ('EndDateCCulture', models.DateField()),
                ('PrepExpCCulture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundProduct',
            fields=[
                ('IdCP', models.IntegerField(primary_key=True, serialize=False)),
                ('NameCP', models.CharField(max_length=20)),
                ('ConcentrationP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MicroChip',
            fields=[
                ('IdMC', models.IntegerField(primary_key=True, serialize=False)),
                ('SizeMC', models.IntegerField()),
                ('NameMC', models.CharField(max_length=20)),
                ('MaterMC', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverFamily',
            fields=[
                ('IdRF', models.IntegerField(primary_key=True, serialize=False)),
                ('NameRF', models.CharField(max_length=20)),
                ('TypeRD', models.CharField(choices=[('IN', 'Inhibitor'), ('AC', 'Activator')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('IdRec', models.IntegerField(primary_key=True, serialize=False)),
                ('PathRec', models.CharField(max_length=150)),
                ('StartDateRec', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpikeFamily',
            fields=[
                ('IdSF', models.IntegerField(primary_key=True, serialize=False)),
                ('NameSF', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTreat', models.DateField()),
                ('EndDateTreat', models.DateField()),
                ('IdCCultureTreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.completeculture')),
                ('IdCPTreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.compoundproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Spike',
            fields=[
                ('IdSpike', models.IntegerField(primary_key=True, serialize=False)),
                ('MeasureSpike', models.IntegerField()),
                ('AmplitudeSpike', models.IntegerField()),
                ('DateSpike', models.DateField()),
                ('NumElectrodeSpike', models.IntegerField()),
                ('TresholdSpike', models.IntegerField()),
                ('FormSpike', models.CharField(max_length=20)),
                ('IdRecSpike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.record')),
                ('IdSFSpike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.spikefamily')),
            ],
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecStartDateCont', models.DateField()),
                ('RecEndDateCont', models.DateField()),
                ('CultureAgeStartCont', models.IntegerField()),
                ('NameExpCont', models.CharField(max_length=100)),
                ('IdCCultureCont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.completeculture')),
                ('IdRecCont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.record')),
            ],
        ),
        migrations.AddField(
            model_name='completeculture',
            name='IdMCCCulture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.microchip'),
        ),
        migrations.CreateModel(
            name='BelongRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCPBelong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.compoundproduct')),
                ('IdRF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.receiverfamily')),
            ],
        ),
    ]
